version: 0.2

env:
  variables:
    FUNCTION_NAME: "nodecheck"  # Replace with your Lambda function name
  build:
    commands:
      # Create the zip file with the Lambda function code and dependencies
      - ls
      - echo "Creating deployment package..."
      - zip -r nodecheck.zip . -x "*.git*" -x "*.zip" -x "kaja/*" -x "kaja"
      - ls

  post_build:
    commands:
      # Upload the zip file to AWS Lambda
      - echo "Uploading deployment package to Lambda..."
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://nodecheck.zip --region us-east-2
artifacts:
  files:
    - nodecheck.zip
